### ISSUE TITLE
Mount permissions issues

### ISSUE THREAD

**Issue by kingrichard2005** [iMartyn/helm-samba4#5]
Hello, my team uses the following shared values to deploy an instance of samba-server to our local development clusters using Rancher Desktop.  Some of us, including myself, are on Windows 10 and running into the below mount errors when deploying some of our applications, we've double checked all permissions and compared between working and non-working deployments to verify deployment and permissions configurations they are the same, but at this point we have not been able to trace the root cause.  

We think this may just be due to a simple misconfiguration, but wanted to post the issue details on here to see if any one else as had similar issues deploying samba-server from Windows 10.  I appreciate any info, please let me know if additional details are needed

```
# Default values for configuring the samba4 server. 
# No changes should be necessary in this section
image:
  tag: latest
persistence:
  enabled: true
  type: pvc
  pvc:
    storageClass: my-local-path
    accessMode: ReadWriteMany
# User information to access samba shares. Adjust as necessary.
samba:
  users:
  - username: FAKE_USER
    password: FAKE_PASSWORD

```

```
Events:                                                                                                                                                                                      │
│   Type     Reason       Age              From               Message                                                                                                                          │
│   ----     ------       ----             ----               -------                                                                                                                          │
│   Normal   Scheduled    9s               default-scheduler  Successfully assigned default/api-service-deployment-54f457bf9b-46fgg to my-laptop                                  │
│   Warning  FailedMount  0s (x5 over 8s)  kubelet            MountVolume.MountDevice failed for volume "pvc-58796b09-5958-48f8-b372-761197d99efd" : rpc error: code = Internal desc = volume( │
│ mysamba-samba4.samba.svc.cluster.local/data/mydata#pvc-58796b09-5958-48f8-b372-761197d99efd##) mount "//mysamba-samba4.samba.svc.cluster.local/data/mydata" on "/var/lib/kubelet/plugins/kubernete │
│ s.io/csi/smb.csi.k8s.io/c0a11fa8fed74f1d11f93de9713f0f24acf98711d8186c201c000e5d6a07e54f/globalmount" failed with mount failed: exit status 32                                               │
│ Mounting command: mount                                                                                                                                                                      │
│ Mounting arguments: -t cifs -o dir_mode=0555,file_mode=0444,vers=3.0,uid=1000,gid=1000,<masked> //mysamba-samba4.samba.svc.cluster.local/data/mydata /var/lib/kubelet/plugins/kubernetes.io/csi │
│ /smb.csi.k8s.io/c0a11fa8fed74f1d11f93de9713f0f24acf98711d8186c201c000e5d6a07e54f/globalmount                                                                                                 │
│ Output: mount error(13): Permission denied                                                                                                                                                   │
│ Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

**Comment by kingrichard2005** [comment]
For anyone who finds this, if it helps, I was able to resolve my issue by manually setting my samba server user below, for reasons TBD the helm-samba4 chart I mentioned earlier at `--version 4.0.1.2` seems to not properly set the password for users you pass in like in the below example values.  This required that I manually set the user from a shell in my samba server like this and only after doing this was my separate deployment able to connect without issue?  Is there a reason I need to manually set my samba users this way even tho I specify them in my values?

```
/ # smbpasswd -a FAKE_USER
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
lp_load_ex: refreshing parameters
Initialising global parameters
Processing section "[global]"
No builtin backend found, trying to load plugin
load_module_absolute_path: Module '/usr/lib/samba/pdb/tdbsam.so' loaded

New SMB password:
Retype new SMB password:
Forcing Primary Group to 'Domain Users' for FAKE_USER
```

https://github.com/iMartyn/helm-samba4/issues/5

```
# Default values for configuring the samba4 server. 
# No changes should be necessary in this section
image:
  tag: latest
persistence:
  enabled: true
  type: pvc
  pvc:
    storageClass: my-local-path
    accessMode: ReadWriteMany
# User information to access samba shares. Adjust as necessary.
samba:
  users:
  - username: FAKE_USER
    password: FAKE_PASSWORD <---Is not getting set even tho it's specified here??
```
